name: run main.py

on:
  schedule:
    - cron: '0 9 * * *' # At 09:00.
  # push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.5" # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # install xvfb
      # since we cannot scrape the site with headless opt (blocked from site)
      # so, we have to install xvfb to performs all graphical operations in virtual memory without showing any screen output.
      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: execute py script # run script
        run: python app.py
